 version: 2
 jobs:
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh -o IdentitiesOnly=yes $SSH_USER@$SSH_HOST "touch t.txt; echo "All Good" > /var/www/html/index.html"
             echo All Good

 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: main # only deploy on the main branch
